### ISSUE TITLE
Javascript field validation on payment page is broken

### ISSUE THREAD

**Issue by khag7** [skyverge/wc-plugin-framework#104]
The script used to validate checkout fields [sv-wc-payment-gateway-frontend.js](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/payment-gateway/assets/js/frontend/sv-wc-payment-gateway-frontend.coffee#L98) is causing an issue on the payment page. To be clear, this is the "order-pay" woocommerce endpoint, not the "checkout" endpoint"

The issue: If a different payment method is selected (such as pay by check) then there shouldn't be field validation. I am selecting pay by check and getting an error that I left the credit card field blank.

The section of javascript causing the issue (this js is generated by the coffee script file referenced above) looks like this:
```
var g = a("#order_review input[name=payment_method]:checked").val();
a("form#order_review").submit(function() {
    return "authorize_net_aim" === g ? b(a(this)) : "authorize_net_aim_echeck" === g ? d(a(this)) : void 0
}
```

The variable `g` gets set on page load and never changes. I'm not sure how to tell coffeescript how to put the variable inside the submit function, but that would solve the problem, like this:
```
a("form#order_review").submit(function() {
    var g = a("#order_review input[name=payment_method]:checked").val();
    return "authorize_net_aim" === g ? b(a(this)) : "authorize_net_aim_echeck" === g ? d(a(this)) : void 0
}
```

**Comment by maxrice** [comment]
@khag7 I can't replicate this with Auth.net CIM, which is the only gateway that uses the frontend JS at the moment. I see `authorize_net_aim` in your examples though. Have you customized the AIM extension?

**Comment by khag7** [comment]
I think I made an assumption that the  auth.net AIM gateway plugin was using the frontend JS from the framework. It appears I was wrong, it uses a frontend JS that is similar but separate. But the problem still exists, its just in a different place than where I originally said it was.

I have just tested on a clean install and the problem exists.

The problem will only appear in the following circumstance:
> 1. Auth.net AIM gateway is the default (go to your WC Checkout settings and move the AIM CC gateway to the top of the list)
2. A user visits the order-pay endpoint
3. No CC info is entered into the credit card text box (if you are using a test Authorize API it will auto fill test CC info, but in real life these boxes show up to a customer empty, so clear them out yourself if you are testing this)
3. The user selects a different method (pay by cheque, for example)
4. They click submit

What happens is:
> 1. when the page loads, value of the element `#order_review input[name=payment_method]:checked` is stored as a variable. Since auth.net AIM was the default selection, the variable is set to authorize_net_aim. A function is bound to the form submit action.
2. The customer changes method to something else. The variable does not change.
3. The customer clicks submit.
4. The bound function fires and checks to see if the selected payment method is authorize_net_aim. 5. Since the variable never changed, that check returns TRUE and the form validation takes place even though it shouldn't.

This also means that all this time, js form validation was never taking place unless the WC Checkout settings were set up that authorize.net AIM was at the top of the list.

**Comment by maxrice** [comment]
@khag7 thanks for the detailed steps to reproduce. I've fixed this and we'll release an update for Auth.net AIM this week :)

**Comment by khag7** [comment]
thanks max. sorry i wasn't so detailed in the first post, it took me a while to figure out the exact scenario that caused the issue.

**Comment by maxrice** [comment]
no worries, I think the auto-fill while in test mode makes it challenging to track down stuff like this that only happens in production :smile_cat:
