### ISSUE TITLE
4.3 Release

### ISSUE THREAD

**Issue by maxrice** [skyverge/wc-plugin-framework#109]
Meta issue to keep track of upcoming changes for the 4.3 release. Our target is late January and should coincide with WooCommerce 2.5.

**Comment by maxrice** [comment]
@skyverge/woocommerce let's discuss these, along with any other changes that you think make sense :smile_cat:

**Comment by ChaseWiseman** [comment]
>Consider base abstract classes for API base request/responses, with different types like JSON/XML

:heart:

**Comment by maxrice** [comment]
moved to #119
