### ISSUE TITLE
Move plugin lifecycle methods out of class-sv-wc-plugin.php 

### ISSUE THREAD

**Issue by unfulvio** [skyverge/wc-plugin-framework#112]
methods like install, activate, deactivate, upgrade, related to lifecycle hooks... and accessory helper methods could be moved into a separate file/class (e.g. class-sv-wc-plugin-lifecycle or class-sv-wc-plugin-installation)

also, to keep things really tidy individual upgrade scripts could be placed in a subfolder `/ugrade`

caveat: this would require a bit of refactoring for all the plugins that implement an install or upgrade method

ref https://github.com/skyverge/wc-plugins/commit/4f55cff894092214cef748cb37ac4c302f8a5ff3#commitcomment-14624678

**Comment by ChaseWiseman** [comment]
Done with 67a9aebbc58c363d35dd065b71beebe0692aac35
