### ISSUE TITLE
WP 4.4 changes in HTTP root certificate bundle and sslfverify in SV framework

### ISSUE THREAD

**Issue by unfulvio** [skyverge/wc-plugin-framework#113]
WP 4.4 changed something in the bundled certificates:

https://github.com/WordPress/WordPress/commit/9f61845204c3be1f1ef1a772e922521af41f74bf

apparently, because of this, some servers that run on Windows or OSX/Yosemite can have some issues, which also affect the behavior of the SV framework

see for example: https://woothemes.zendesk.com/agent/tickets/363247

this seems to be connected with sslverify here: https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/api/class-sv-wc-api-base.php#L316

props to Gabor from Prospress for this finding -- they are turning sslverify to false to tackle this

**Comment by unfulvio** [comment]
lol, apparently, it's WP's fault

https://twitter.com/HRH_Duke_of_Url/status/674506288429166593

**Comment by unfulvio** [comment]
https://core.trac.wordpress.org/ticket/34935

**Comment by maxrice** [comment]
@unfulvio nothing we can do about this on our end, we're not going to change our `sslverify` value. We can draft a reply for tickets with this issue and provide a small (temporary) snippet to disable that setting while they work with their hosts to upgrade cURL/openssl :smile_cat:
