### ISSUE TITLE
Can't view orders when My Account is set as the front page

### ISSUE THREAD

**Issue by tamarazuk** [skyverge/wc-plugin-framework#124]
It seems the payment gateway framework might be interfering with WooCommerce core rewrite rules

To replicate active a frameworked payment gateway such as Authorize.net CIM or Braintree and set the My Account page as the static front page under **Settings > Reading**. Then try to view an order from the My Account page.

Originally reported in: https://github.com/skyverge/wc-plugins/issues/1120#issuecomment-168599704
Related ticket: https://woothemes.zendesk.com/agent/tickets/370882
Subscriptions fix: https://github.com/Prospress/woocommerce-subscriptions/pull/1089

**Comment by maxrice** [comment]
Replicated as WC core issue, added https://github.com/woothemes/woocommerce/issues/10062
