### ISSUE TITLE
Invalid arguments warning in `SV_WC_Helper::get_order_line_items()`

### ISSUE THREAD

**Issue by tamarazuk** [skyverge/wc-plugin-framework#127]
Due to two `implode()` calls on the items description in `SV_WC_Helper::get_order_line_items()`, the following error is thrown

```
Warning: implode(): Invalid arguments passed in /../lib/skyverge/woocommerce/class-sv-wc-helper.php on line 441
```

This bug was introduced in SHA 01086edef7904a8121f5060d1b8bb69d4fa2ca51 and reported in [ZD Ticket 376259](https://woothemes.zendesk.com/agent/tickets/376259)

**Comment by tamarazuk** [comment]
@maxrice can you give this method and commit a quick review to ensure i didn't miss anything else :stuck_out_tongue_winking_eye: Thanks!

**Comment by maxrice** [comment]
LGTM
