### ISSUE TITLE
Add credentials check to payment gateway API interface

### ISSUE THREAD

**Issue by maxrice** [skyverge/wc-plugin-framework#130]
A common issue with gateways is invalid credentials, which will present at checkout (generally) as an error which the admin must review in the order notes for the failed order (unless they have debug mode enabled to the checkout). If a gateway supports a way to do a credentials check (e.g. with Authorize.net CIM, we can request the hosted payment page which has no affect on the account, but will indicate if the provided credentials are valid), we could add this to our payment gateway API interface and add some admin notices around it.

We could potentially even go further with this and persist some sort of "connection status" in the gateway settings (a la the AvaTax extension) as additional admin messaging.

**Comment by ChaseWiseman** [comment]
closing in favor of #150
