### ISSUE TITLE
More flexible translation loading

### ISSUE THREAD

**Issue by maxrice** [skyverge/wc-plugin-framework#136]
Sometimes users want to load their own translation files for various reasons. As it stands right now, this is somewhat difficult to do with both the framework translation files and individual plugin files. We should consider following what [WC core does](https://github.com/woothemes/woocommerce/blob/2.5.5/woocommerce.php#L333-L347) which should make it easier to load translations from a different location that isn't overwritten by plugin updates.

As part of this, it'd be nice to automatically handle the `load_plugin_textdomain()` method inside the framework as well, rather than requiring the plugin to implement the abstract `load_translation()` method. I see no reason why we can't pass the text domain as an arg to the constructor and have the framework code load the plugin's translation files.

**Comment by unfulvio** [comment]
cool, I didn't realize we weren't supporting this by default

WC core code/function looks like that also in regards of language packs support

http://ottopress.com/2013/language-packs-101-prepwork/

we should do something here also in regards of language packs distributions, according how WT is handling that -  it'd be neat if we can roll language updates for plugins without rolling out actual plugin updates

**Comment by maxrice** [comment]
>cool, I didn't realize we weren't supporting this by default

Yeah I looked a little deeper and there is filters in WP core that would let you define your own files, but we can certainly make it easier to do.
