### ISSUE TITLE
Update SV_WC_API_Base to support forced TLS v1.2 connection

### ISSUE THREAD

**Issue by maxrice** [skyverge/wc-plugin-framework#139]
Some gateways and integrations may require TLS v1.2 connections in the future. PayPal will require this as of June 2016. We should add a method within our `SV_WC_API_Base` class that implementing classes can use to require the connection to be TLS v1.2. This option is only available as of cURL 7.34.0 so we may need to conditionally check that.

Some relevant links:

https://core.trac.wordpress.org/ticket/36320
https://core.trac.wordpress.org/ticket/34924
https://github.com/woothemes/woocommerce/pull/10639

reported in [HS 23763](https://secure.helpscout.net/conversation/189374867/23763/?folderId=46425)

**Comment by reidbiztech** [comment]
TLS 1.2 connections (when CURLOPT_SSLVERSION is set to 6), are working on our host's server which has curl 7.19.7 (CentOS 6.7). I suspect it is just the **auto-negotiation** when CURLOPT_SSLVERSION is set to 1 that does not work with curl versions less than 7.34.0 - but I have not examined the cURL code to determine if this is in fact the case. I believe it will also be dependent on the version of OpenSSL that is present on the server in question (OpenSSL 1.0.1e-fips on our server).
