### ISSUE TITLE
should_display_notice() and show_messages() methods only check for manage_woocommerce cap

### ISSUE THREAD

**Issue by unfulvio** [skyverge/wc-plugin-framework#140]
Some methods in the admin notice and message handler classes check if the current user can manage WooCommerce to decide whether to output an admin notice or not.

at least:

here https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/class-sv-wp-admin-message-handler.php#L240

and here https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/class-sv-wc-admin-notice-handler.php#L111

However, there's the possibility that a user has some lower WC capability which would lose those messages. 

I came across this issue in this [ZD Ticket 407506](https://woothemes.zendesk.com/agent/tickets/407506) for PIP... We use admin messages to show a link to open a print window to print invoices and packing lists. In this case the shop manager had users with only `manage_woocommerce_orders` capability who couldn't see this notice and thus not being able to print documents.

While we might change how this works in future releases of PIP I think this could be an issue in the framework. Should we pass an additional parameter, like an array of extra caps to check?

**Comment by maxrice** [comment]
an additional parameter for allowed caps (in addition to `manage_woocommerce`) seems like a fine solution to me

**Comment by unfulvio** [comment]
sorry forgot to reference issue number in commit, which is https://github.com/skyverge/wc-plugin-framework/commit/188479bb3c44030b546dba894224e25752279a85
