### ISSUE TITLE
Adjust token editor table title to use plugin name

### ISSUE THREAD

**Issue by maxrice** [skyverge/wc-plugin-framework#141]
The token editor table should just use plugin name as title, then each gateway should have environment in parens:

* curent: http://cloud.skyver.ge/3d160X1K0G1O
* proposed: http://cloud.skyver.ge/1E3O3f2D0v32

**Comment by maxrice** [comment]
@ChaseWiseman I think it's worth putting this into 4.3.0, whatcha say?

**Comment by ChaseWiseman** [comment]
complete! https://github.com/skyverge/wc-plugin-framework/commit/cbf4fa4372a188e35c799c8f7307c141becdc700
