### ISSUE TITLE
Fix incorrect thank you page message when performing auth-only transaction and detailed decline messages are enabled

### ISSUE THREAD

**Issue by maxrice** [skyverge/wc-plugin-framework#142]
When performing an authorize-only transaction and detailed decline messages are enabled, certain gateways may return a generic "error" message that is displayed to the customer incorrectly, due to [this line](https://github.com/skyverge/wc-plugin-framework/blob/4.2.0/woocommerce/payment-gateway/class-sv-wc-payment-gateway.php#L1829).

We should look to refactor the messaging when marking an order as held if authorize-only transaction was successful. A simple fix in the meantime is to change that line to:

`if ( ! $user_message || ( $this->supports_credit_card_authorization() && $this->perform_credit_card_authorization() ) ) {...`

**Comment by ChaseWiseman** [comment]
added with SHA d48b30a74fa54cd7130f28cbbb5a02fcb93b1fcc
