### ISSUE TITLE
Incompatible suhosin settings notice

### ISSUE THREAD

**Issue by tamarazuk** [skyverge/wc-plugin-framework#143]
We've seen a number of tickets where customers aren't able to save settings, particularly for gateways, when suhosin settings are left at their defaults.  [ZD Ticket 409028](https://woothemes.zendesk.com/agent/tickets/409028) is just the latest example.

It was suggested in [Slack](https://skyverge.slack.com/archives/wc-support/p1461257647000326) that we add a check and display a notice when suhosin settings would conflict with a particular plugin. 

We can either list conflicting properties and their values per plugin, or we can determine a general minimum between all of our plugins (or just gateways) and always display a notice when the settings are below this minimum.

I think it would also be nice to add some of these values to the system status report. Many customers miss the notices because they have so many. Having some concrete numbers and errors in the System Status Report will definitely help in support. 

Keeping track of all the tickets:

http://woothemes.zendesk.com/agent/tickets/433211

**Comment by ChaseWiseman** [comment]
I like the idea of keeping the minimum, error notice, and system status report entries general across the plugins, perhaps with a way for individual plugins to override/add their own easily.

**Comment by ChaseWiseman** [comment]
@tamarazuk whenever you get a minute, could you let me know what you think of my approach here? https://github.com/skyverge/wc-plugin-framework/commit/d11d4a8227bcce8f61c20c0c0d4a40c640f1f762

I went with appending our own rows to the **Server Environment** section of the System Status report. The framework defines some default SUHOSIN minimums, and plugins can override these and/or define their own via the constructor args, just like extension dependencies.

I looked at the idea of admin notices as was originally mentioned, but I can't think of a clean way to avoid duplicate notices for each active plugin.

What do you think? Does listing known incompatibilities in the report add significant support value? Happy to tweak further as we test if you have suggestions :)

**Comment by ChaseWiseman** [comment]
Also, I took the suhosin defaults from https://docs.woocommerce.com/document/problems-with-large-amounts-of-data-not-saving-variations-rates-etc/ - does that seem reasonable as a base?

**Comment by tamarazuk** [comment]
@ChaseWiseman A system status report entry is definitely great for the power users - those that will investigate the issue on their own before opening a ticket. This will also help out in support and does add some value as we're able to see the actual values and point the customer in the right direction by letting them know which settings should be increased. 

However, I do think a notice would be nice if at all possible. Can we leverage what we do for the incompatible framework update? Alternatively, can we just add that notice to the plugin settings page, so it doesn't ever get duplicated on the same page (or at least rarely).

Yes, I think those values are a reasonable base 👍

**Comment by ChaseWiseman** [comment]
ah okay, yes as long as we're cool with the notice only being displayed on the settings page then that's doable. I want to avoid adding to the WP admin notice noise 🍻 

I don't think there's a way to get the plugin dependency info at the bootstrap level, so the back-compat style notice isn't really an option.

**Comment by tamarazuk** [comment]
> ah okay, yes as long as we're cool with the notice only being displayed on the settings page then that's doable. I want to avoid adding to the WP admin notice noise 🍻

> I don't think there's a way to get the plugin dependency info at the bootstrap level, so the back-compat style notice isn't really an option.

A plugins settings notice would be perfect. That's generally where people would already run into the issue, or go to figured out what could be wrong. Thanks!
