### ISSUE TITLE
Evaluate `wp_remote_request` usage

### ISSUE THREAD

**Issue by bekarice** [skyverge/wc-plugin-framework#151]
WordPress 4.6 changes the returned response for `wp_remote_request` from an array to an object -- [see details here](https://core.trac.wordpress.org/ticket/33055#comment:51). We need to evaluate our usage for this to add WP 4.6 compatibility.

**Comment by ChaseWiseman** [comment]
This is all set as of v4.4.1: https://github.com/skyverge/wc-plugin-framework/pull/160
