### ISSUE TITLE
Consider mapping deprecated hooks

### ISSUE THREAD

**Issue by ragulka** [skyverge/wc-plugin-framework#154]
Hook deprecator currently simply displays a warning when a hook is deprecated, but it would be really-really nice if it would also map any renamed hooks. For example, if a hooks was called `plugin_hook` and  it was renamed to `plugin_new_hook`, then any functions/methods hooked to `new_filter` would automatically be mapped to `plugin_new_hook`.

There's a writeup my Mike Jolley on how they are doing this in WooCommerce: https://mikejolley.com/2013/12/15/deprecating-plugin-functions-hooks-woocommmerce/

This could be generalized even more, so that we don't need to know how many args to pass:

``` php
/** @var array deprectaed filter mapping, old => new **/
protected $deprecated_filters = array(
    'wc_customer_order_csv_export_admin_query_args'      => 'wc_customer_order_csv_export_query_args',
    'wc_customer_order_csv_export_admin_user_query_args' => 'wc_customer_order_csv_export_user_query_args',
);

public function __construct() {

    // Handle renamed filters
    foreach ( $this->deprecated_filters as $new_filter ) {
        add_filter( $new_filter, array( $this, 'map_deprecated_filter' ) );
    }
}

public function map_deprecated_filter() {

    $args   = func_get_args();
    $data   = $args[0];
    $filter = current_filter();

    // check if there is a matching old filter for teh current filter
    if ( $old_filter = array_search( $filter, $this->deprecated_filters ) ) {

        // check if there are any filters added to the old filter
        if ( has_filter( $old_filter ) ) {

            // prepend old filter name to the args
            array_unshift( $args, $old_filter );

            // apply the filters attached to the old filter hook to $data
            $data = call_user_func_array( 'apply_filters', $args );

            _deprecated_function( 'The ' . $old_filter . ' filter', '3.12.0-1', $filter );
        }
    }

    return $data;
}
```

**Comment by bekarice** [comment]
a quick note, as we saw [with CSV / XML Exprot](https://github.com/skyverge/wc-plugins/commit/fc1840577e30d457a0fbedb14667ba267a6178e6) in testing, we'd need to pass a default priority and number of args when applying the old / mapped filters
