### ISSUE TITLE
Consider including the admin notice handler class file in the method that returns its instance

### ISSUE THREAD

**Issue by unfulvio** [skyverge/wc-plugin-framework#167]
In CSV Export we have a case where the admin notice handler is needed in `DOING_CRON` context. While `DOING_CRON`, we have a condition where `is_admin()` is `false`. But the FW only loads this class in admin context.

A fix in CSV Export consisted requiring again the class file before returning the object, like so:

https://github.com/skyverge/wc-plugins/commit/42eb5a13e74effe62f62e13a6febf2ec7ec6e694

we could adopt a similar pattern in FW

issue for [CSV Export](https://github.com/skyverge/wc-plugins/issues/1651) from @ragulka :

>  admin notice handler class is not loaded when doing cron, but we need to use it for setting failed background job notices. This is because the framework [loads the admin notice handler](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/class-sv-wc-plugin.php#L240-L243) only when `is_admin()`, but the `get_admin_notice_handler()` [method does not check if the class exists](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/class-sv-wc-plugin.php#L612-L619) before instantiating it. Which lead me to believe that the class was always available. We should probably fix this in the framework, by moving the class file require line to the method that needs to instantiate the class on demand, but until then, we probably should overwrite the method in plugin.

see also:  [Slack convo](https://skyverge.slack.com/archives/wc-support/p1472810044000002)

**Comment by ragulka** [comment]
I just bumped into a similar issue in PDF vouchers, but this time with the Message_Handler class. Could we consider the same approach for `get_admin_message_handler()` as well?
