### ISSUE TITLE
Update Payment Method UI

### ISSUE THREAD

**Issue by ChaseWiseman** [skyverge/wc-plugin-framework#178]
It would be cool to add a basic UI for updating credit card expiration dates from My Account. Gateways like Authorize.Net CIM now support this via their API, and there are probably more to come.

It shouldn't be too involved to add an "Edit" action button next to "Delete" that reveals some expiration date inputs or something similar. Then we could add a new feature flag and some stub methods to handle everything else.

At checkout, this would also allow us to adjust the way expired cards are shown. Rather than showing the expiration date: `(expires mm/yy)` we can show `(expired - update)`, linking the "update" text to to our new update endpoint (or perhaps doing it inline, not sure if this would be possible yet). Highlighting / making the expired text red would also help draw attention to this.

As a final level of polish, if this is possible, we could disable placing an order for an expired method, but not sure if that's too obtrusive.

**Comment by maxrice** [comment]
😍

**Comment by ChaseWiseman** [comment]
Here are some examples from what I've been experimenting with:

### My Payment Methods
![my-payment-methods](http://cloud.skyver.ge/1E270Z3s0C16/Image%202017-06-02%20at%2011.54.48%20AM.png)

Along with general styling tweaks, this would add the concept of method "nicknames" to let customers specify a name for each card. This could be supported by any gateway since it's not likely to include any API communication and it's purely for display. Then, each method can be edited inline:

![my-payment-methods-edit](http://cloud.skyver.ge/0V0o3A320l1s/Screen%20Shot%202017-06-02%20at%2011.57.22%20AM.png)

There would also be fields for the expiration dates for gateways that support it, but I haven't got that far yet.

### Checkout
Some of this would carry over to the checkout form, allowing customers to specify a method Nickname then, if they check the "Save method" checkbox.

![my-payment-methods-checkout](http://cloud.skyver.ge/1g1m300c1S2q/Screen%20Shot%202017-06-02%20at%2012.14.25%20PM.png)

Overall I think these would be some solid UX improvements!

**Comment by bekarice** [comment]
@ChaseWiseman i think this is intended to be related to #198 as well? 

- new default batch is nice and clean in comparison to the old layout
- Like the nickname idea a lot, I know I use that myself for personal vs business amex
- I might give a visual indicator that the name can be edited inline, such as a small pencil icon next to the name, or a text decoration
- not 100% sure on adding that 'nickname' to checkout since sometimes people think all fields are required. likely fine as-is, but we could also consider asking them to name that card on the "order received" page instead: "Thanks for adding a saved payment method! Want to [add a nickname](#) to this account for future use?"

**Comment by ChaseWiseman** [comment]
@bekarice yeah #198 will likely be absorbed back into this one once we get a little further.

>I might give a visual indicator that the name can be edited inline, such as a small pencil icon next to the name, or a text decoration

Yes, there will be an Edit action button as well which reveals all of the editable fields like Nickname & expiry. Just didn't make it into these screenshots 😸 

>not 100% sure on adding that 'nickname' to checkout since sometimes people think all fields are required

good point. I guess the simplest way would be to append ` (optional)` to the input label, but I do like your Thank You page idea as well.

**Comment by bekarice** [comment]
👍  awesome. I think I see what you're saying now -- "Edit" action would let you set both nickname + update expiration inline, then re-save? Could experiment with that vs click to edit in-line and re-save automatically and see which feels better
