### ISSUE TITLE
Subscriptions Tokenization warning styles don't load when "WooCommerce" is translated

### ISSUE THREAD

**Issue by bekarice** [skyverge/wc-plugin-framework#183]
(See https://github.com/skyverge/wc-plugins/issues/1818 or https://github.com/skyverge/wc-plugins/issues/1817 for more details)

When a gateway that supports Subscriptions is available, but doesn't have tokenization enabled, we warn the user in the payment methods table:
![screen shot 2016-12-05 at 1 37 13 am](https://cloud.githubusercontent.com/assets/4983547/20876024/237d073c-ba8d-11e6-985b-51872ac80f82.png)

However, when the "WooCommerce" string is translated, these styles are not added:
![screen shot 2016-12-05 at 1 43 05 am](https://cloud.githubusercontent.com/assets/4983547/20876041/33e85e3c-ba8d-11e6-8084-82c963439f81.png)

This is due to the fact that we're trying to use `wp_add_inline_style()` using [a specific screen via `admin_print_styles-{hook}` here](
https://github.com/skyverge/wc-plugin-framework/blob/312241373eb3ef412afbae34d5627a2c1cf79b12/woocommerce/payment-gateway/class-sv-wc-payment-gateway-plugin.php#L156). However, WordPress uses the sanitized menu _title_, not the menu slug, to generate that screen id, so if `__( 'WooCommerce', 'woocommerce' )` is translated, this breaks that hook (along with screen id checks looking for `woocommerce_page_` specifically). See [Trac ticket #21454](https://core.trac.wordpress.org/ticket/21454) and [Trac ticket #18857](https://core.trac.wordpress.org/ticket/18857) for details.

Since we can't depend on that hook existing with translations, and I don't think there's a way to know _what_ the translation would be early enough, we're probably better off just using `admin_print_styles` or another action, then adding a current screen check into `subscriptions_add_renewal_support_status_inline_style()` (running `woocommerce` through `sanitize_title()` of course to get the right screen ID). Not sure if there's a more elegant way around that.

**Comment by bekarice** [comment]
SHA 7929f448bb0a89e37526601c05568cd8c9cb4b33 adds a helper we can use to get the proper screen id with FW 4.6+

**Comment by bekarice** [comment]
@ChaseWiseman quick note: SHA 26d1540f2e6cb653e21e8769e610aca69ab08748 doesn't close this; we'd still need to leverage it by perhaps [changing this hook name](https://github.com/skyverge/wc-plugin-framework/blob/312241373eb3ef412afbae34d5627a2c1cf79b12/woocommerce/payment-gateway/class-sv-wc-payment-gateway-plugin.php#L156) to `admin_print_styles` or `admin_enqueue_scripts` and then doing a manual screen ID check leveraging our helper method. 

The hook name itself is borked by the translation so our function to add the inline styles never runs. 

Happy to add this myself if you're not pickup what I'm putting down as well, just let me know if you want me to push it for your review.

**Comment by bekarice** [comment]
nvm, just added so you can see what I mean: SHA 22e8c660721452bfb1d26722bee17d29a1aa2681

**Comment by ChaseWiseman** [comment]
@bekarice ah thanks for that, got on a roll with my `closes` comments 😸
