### ISSUE TITLE
Add cURL & TLS 1.2 admin notices

### ISSUE THREAD

**Issue by ChaseWiseman** [skyverge/wc-plugin-framework#188]
In #139 we added the ability for plugins to specify that their API requires TLS 1.2. Let's enhance this by adding a few admin notices if cURL is out of date or TLS 1.2 is not supported.

**Comment by maxrice** [comment]
We've seen an issue ([ZD 549724](https://woothemes.zendesk.com/agent/tickets/549724)) where forcing TLS v1.2 on cURL had no effect -- the initial connection was still attempted over SSLv3. While the customer ultimately had to upgrade their server to resolve the issue, they did mention that this snippet fixed the issue temporarily:

`curl_setopt($handle, CURLOPT_SSL_CIPHER_LIST, 'AES256-SHA');`

Might be something to consider adding either to our API base, or in the docs.

**Comment by maxrice** [comment]
Authorize.net will [require TLS 1.2 in production starting on Sept 18, 2017](http://app.payment.authorize.net/e/es.aspx?s=986383348&e=1407311&elqTrackId=b4d9a2a0f1424fe28f720ff9d8ae4d54&elq=d937d53e3a4a494b87c2918dc6bf08a3&elqaid=577&elqat=1)
