### ISSUE TITLE
Add select2 v4.0.3 support in FW v4.6.0 for WC 2.7 compat

### ISSUE THREAD

**Issue by unfulvio** [skyverge/wc-plugin-framework#193]
## PR in #194 

`SV_WC_Helper::render_select2_ajax()` is currently not compatible with Select2 v4.0.3 bundled with WC 2.7. The API has changed since Select2 v3.5.3 shipped with WC until so far.

Proposed changes:

- target `<select>` elements only, since they are the only ones supported by Select2 now (also a faster selector than `:input`
- being all dropdown elements, `multiple` can be handled directly in the HTML attribute; so all the JS logic to set multiple can be discarded (in particular we no longer need to account to split comma separated items in `value` to build an array: they are already an array)
- some arguments have changed, like quietmillis -> delay and also, we need to change how callbacks for `data` and `results` (now `processResults`) are handled

Other changes:

Any plugin using this **must** update selector from `input type="hidden"` or type text to `select`. Enhanced dropdowns which are already `select` elements probably require no change. However, in either case, if you have selected options (single or multiple), then you need to make sure to add the corresponding `<option>` choices with `selected` attribute so they will be selected on page load.

**Comment by unfulvio** [comment]
@ChaseWiseman I've tested this in ACOF and other plugins seem to work well, please have a look too, you're the Framework Master :tm:

**Comment by ChaseWiseman** [comment]
Perfect, thanks for this!
