### ISSUE TITLE
Fix WC 3.0+ Warnings with Subscriptions

### ISSUE THREAD

**Issue by bekarice** [skyverge/wc-plugin-framework#202]
When using Subscriptions and WC 3.0+, WooCommerce will trigger deprecated notices for accessing order properties directly. This is is due to some props we missed in the [gateway subscription integration class](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/payment-gateway/integrations/class-sv-wc-payment-gateway-integration-subscriptions.php) using properties like `$subscription->id` and `$subscription->payment_method`.

These should be updated to use the `SV_WC_Order_Compatibility` methods as well.

   * **Reported by**: Beka during testing

**Comment by daigo75** [comment]
If it may help, the Subscriptions plugin 2.2 provides wrapper methods to access the properties:
- `wcs_get_objects_property()`
- `wcs_set_objects_property()`

They could save some time, as they already include the logic to work with both WC 3.0.x and earlier versions.
