### ISSUE TITLE
Old gateway payment meta is not removed after Change Payment

### ISSUE THREAD

**Issue by ChaseWiseman** [skyverge/wc-plugin-framework#216]
When changing payment on a Subscription between two gateways within the same plugin, the old gateway's token meta is not removed. This doesn't affect subsequent renewals, but can block the customer from later deleting the old payment method since My Payment Methods sees them as both being tied to the subscription. I _think_ this is only with WC 3.0+ & Subscriptions 2.2+

![no-good](http://cloud.skyver.ge/122n443i2x29/Screen%20Shot%202017-05-04%20at%202.00.49%20PM.png)

Screenshot & reported by @bekarice 🍻

**Comment by bekarice** [comment]
Beka: Accidentally Breaking Things since 1987™

**Comment by ChaseWiseman** [comment]
UI issues fixed with 04c93cea1e6729edbdbc953a9b95aae5747cb5ef

Keeping this open though since the meta issue still needs investigation.
