### ISSUE TITLE
Always Allow Payment Captures

### ISSUE THREAD

**Issue by bekarice** [skyverge/wc-plugin-framework#217]
Right now, if a gateway is disabled, the capture action isn't available for orders. While this isn't needed in most cases, if the gateway is still active but disabled to process existing subscriptions, and these are authorized, you'll still need to capture them :) We can likely leave capturing enabled, at least on the single order action if not the bulk one, even when the gateway is disabled.

(Or potentially if the gateway is disabled + Subscriptions active).

**Comment by ChaseWiseman** [comment]
This was taken care of as part of adding partial captures in v5 😄
