### ISSUE TITLE
Possibly adjust "Accepted Cards" behavior and labeling

### ISSUE THREAD

**Issue by ChaseWiseman** [skyverge/wc-plugin-framework#218]
An issue was raised about the **Accepted Card Types** setting being misleading in that it doesn't actually limit the use of certain card types, but rather changes the card type icons and inline form validation. See https://github.com/woocommerce/woocommerce-gateway-authorize-net-aim/issues/6#issuecomment-301561784

There may be nothing to change here, but let's take a look at ways that could improve the UX of this. Perhaps:

- Have gateways override the Help Tip text for specific instructions for enabling/disabling card types with their payment processor
- Change the Payment Form JS validation to halt checkout if an "unsupported" card type is used

A bit of research needed.

**Comment by bekarice** [comment]
another one that was seeking clarification here: zd-589246

Potentially an always-visible description could be a starting point rather than the tooltip (or both)
