### ISSUE TITLE
Prevent resetting the password field on checkout refresh

### ISSUE THREAD

**Issue by ChaseWiseman** [skyverge/wc-plugin-framework#255]
Our payment form JS listens for `change` on the Create Account checkbox to show/hide our tokenize method checkbox for logged out users. In order to ensure the correct state on initial page load, we call [`.change()` on the input ourselves](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/payment-gateway/assets/js/frontend/sv-wc-payment-gateway-payment-form.coffee#L334), but this also runs every time the checkout is updated resulting in the checkbox being toggled unnecessarily, which causes the password field to clear.

This is a bummer for customers who input a password and later change a billing field, which requires them to input the password again.

**Comment by unfulvio** [comment]
:apple:
