### ISSUE TITLE
Why don't you upload localization files to translate.wordpress.org?

### ISSUE THREAD

**Issue by meglio** [skyverge/wc-plugin-framework#280]
Hi. I'd like to help translating the WC Plugin Framework and some of plugins based on it to Russian (e.g. WooCommerce Measurement Price Calculator). None of the localization files are available at translate.wordpress.org. Is there any reason why not?

**Comment by unfulvio** [comment]
Hey @meglio thanks for reaching out. We would really love to address this and support more languages.

Currently plugins listed on WooCommerce.com, like Measurement Price Calculator, are not available for donwload on WordPress.org, where language packs are pushed and community translations are done. As far as I know there was a project to blend these tools with commercial plugins like WooCommerce extensions but it did not have much follow up beyond initial experimentation (I hope to be wrong).

Of course, bundled translations or custom translations are fully supported. You will find updated `.pot` files for every SkyVerge plugin, normally in the `i18n` folder. 

If you wish to supply a Russian translation for Measurement Price Calculator we'd be happy to include that in the plugin release and credit you for that.

In the future we would like to include some professional translation without users asking for it or having to provide their files; we would need to figure out a viable alternative to language packs which we can't use at the moment.

**Comment by meglio** [comment]
You could at least setup your local Glotpress instance (that's what
translate.wordpress.org uses) – it is just an Open Source WordPress plugin
that converts a WordPress instance into a translator collaboration
platform; it will allow for users to contribute translations online, and
for you coordinate their help.

That's what I did to start translating the plugin – I just quickly setup
Glotpress and using it now. But the drawback is that my work is not
publicly visible this way, and I won't be able to export and re-submit the
localisation files every single time I improve / update the translation
while I use the plugin.

**Comment by ChaseWiseman** [comment]
Thanks for the feedback! We don't have setting up our own Glotpress implementation on the roadmap right now, but we'll take your comments into consideration.

Cheers!
