### ISSUE TITLE
Delete stored payment methods with personal data erasure

### ISSUE THREAD

**Issue by bekarice** [skyverge/wc-plugin-framework#289]
### Backport to FW v4 as well

Remove stored payment method data during erasure requests:

 - Hook into `woocommerce_privacy_remove_order_personal_data` to remove stored payment type and card last 4 from orders when anonymized.
 - Hook into `woocommerce_privacy_erase_personal_data_customer` to remove both local and remote payment tokens when customer accounts are cleared.

**Comment by ChaseWiseman** [comment]
Alright, in #291 I've added a gateway privacy handling class that will:

* Add payment method details to exports (customer ID, tokens, and per-order payment details)
* Remove tokens locally and remotely on customer erasure
* Remove customer ID meta on erasure
* Anonymize order payment last four, type, and expiry

Will now be porting this to v4 👍
