### ISSUE TITLE
Capture order note doesn't use order currency

### ISSUE THREAD

**Issue by tamarazuk** [skyverge/wc-plugin-framework#290]
The credit card capture order note uses the site's default currency symbol instead of the order's currency causing confusion when multi-currency plugins are used.

https://github.com/skyverge/wc-plugin-framework/blob/3cd3f2413c0288104cadf83f2c08fcfb6a2e51b0/woocommerce/payment-gateway/class-sv-wc-payment-gateway.php#L1765

The above should be replaced to replicate how the refund order note is added:

https://github.com/skyverge/wc-plugin-framework/blob/3cd3f2413c0288104cadf83f2c08fcfb6a2e51b0/woocommerce/payment-gateway/class-sv-wc-payment-gateway.php#L2144

and use `wc_price()` with the order's currency as an argument. 

* **Reported in:** [HS convo 76891](https://secure.helpscout.net/conversation/580585288/76891)

**Comment by Ashleygross** [comment]
Just opening

**Comment by ChaseWiseman** [comment]
Fixed with #298
