### ISSUE TITLE
TypeError: this.payment_fields is undefined

### ISSUE THREAD

**Issue by mirzazeyrek** [skyverge/wc-plugin-framework#310]
We were facing with this error on our checkout page:

https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/payment-gateway/assets/js/frontend/sv-wc-payment-gateway-payment-form.min.js#L115

After adding this line before line 115 in `sv-wc-payment-gateway-payment-form.min.js` it is solved:

```
                // Custom fix for undefined find error.
                if(typeof this.payment_fields === 'undefined'){
                    this.set_payment_fields();
                }
```

Any ideas if this is a bug of wc-plugin-framework or something on our side ?

**Comment by bekarice** [comment]
@mirzazeyrek sounds like you're using Autoptomize? Please remove that plugin or ensure assets are in the header and `sv-wc-payment-gateway-payment-form.min.js` exclusion is added (that's the only time we've ever seen this issue). If you run into further questions, our support team would be happy to help -- you can [reach them here](https://woocommerce.com/my-account/create-a-ticket/). 😸
