### ISSUE TITLE
Regression in payment capture alert

### ISSUE THREAD

**Issue by bekarice** [skyverge/wc-plugin-framework#317]
Payment capture alerts should not use `wc_price()` to format capture amount, or should avoid escaping this HTML. Best guess is a regression due to #309, so we should strip tags first.

![screen shot 2018-08-31 at 5 15 54 pm](https://user-images.githubusercontent.com/4983547/44936733-e61eea80-ad43-11e8-8ae8-df0fdf826a6a.png)

**Comment by unfulvio** [comment]
:melon:
