### ISSUE TITLE
Improve payment form

### ISSUE THREAD

**Issue by justinstern** [skyverge/wc-plugin-framework#4]
The current payment form is out-dated and is a big PITA to update. We generate it (and the associated JS/Coffee) on a per-plugin basis from a template which makes it very challenging to make bulk updates.

## Payment form
* Make it a standard set of methods that gateways can declare support for and have output automatically. Methods should be easily overridden as needed.

## JS/Coffee
* Enqueue a standard framework JS script that handles the default payment form and makes it easy to extend for custom reasons (see the "asset check" needed for NETbilling)
* Make use of jQuery.payment, which is bundled in WC core as of 2.1

## Card/Check images
* Add shiny new retina-ready versions
* Replace our horrible looking "check" image with something nicer
* http://www.dreamstale.com/free-download-payment-method-vector-icons
* https://github.com/orlandotm/payment-webfont
* http://paymentfont.io/#icons

## References
* http://gosseti.com/demos/a-better-card-payment-form

**Comment by maxrice** [comment]
closed in https://github.com/skyverge/wc-plugins/commit/02bc91e94684b6dc229446c4c50db7f9e9033b03
