### ISSUE TITLE
Improve Held Order Handling

### ISSUE THREAD

**Issue by justinstern** [skyverge/wc-plugin-framework#51]
The held orders aren't handled as well as failed orders.  We should probably have a `do_transaction_held_result()` method, with a default very similar to `do_transaction_failed_result()` and which tries to set as much additional information from the transaction response as possible so that the order can be easily and properly handled.

Look at Chase error testing for samples

**Comment by maxrice** [comment]
@justinstern can you reference the Chase implementation here? Held orders seemed to be handled decently by [this](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/payment-gateway/class-sv-wc-payment-gateway-direct.php#L813-L879) and [this](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/payment-gateway/class-sv-wc-payment-gateway.php#L1542-L1573)

**Comment by justinstern** [comment]
yeah you know to be honest I don't think this issue applies any longer
