### ISSUE TITLE
SV_WP_Background_Job_Handler::maybe_handle() throws deprecated notices from Woo 5.3

### ISSUE THREAD

**Issue by claudiosanches** [skyverge/wc-plugin-framework#541]
Hello team!

Recently we [fixed an old bug in Woo core](https://github.com/woocommerce/woocommerce/pull/29542), and seems like that this framework is also trying to deal with it, and throws some PHP notices since this framework is calling our old and deprecated `WC()->session->nonce_user_logged_out()` method, now in 5.3 doesn't seems necessary any workaround like this: 
https://github.com/skyverge/wc-plugin-framework/blob/403a2d0d5ad4cf2f1b38675f0f9d41b33353f622/woocommerce/utilities/class-sv-wp-background-job-handler.php#L153-L166

We found out it by some support requests coming from the Facebook integration: https://wordpress.org/support/topic/nonce_user_logged_out-function-is-deprecated/

**Comment by unfulvio** [comment]
hey @claudiosanches thanks for the heads up sorry if this fell under our radar - thankfully another user in #545 brought it up as well and we can get this patched

**Comment by unfulvio** [comment]
issue is fixed in v5.10.13 of the FW, individual plugins that use background jobs will need to update to this version, thanks again for reporting this!
