### ISSUE TITLE
Cancelled payment return URL

### ISSUE THREAD

**Issue by ragulka** [skyverge/wc-plugin-framework#56]
I was playing around with the framework and noticed that when I cancelled a payment, I was redirected to the Thank You page which said "Thank You. Your order has been received". That was odd. So I checked in the store admin, and the order was marked as cancelled.

I then checked my code to see any possible errors there, but could not find any. FInally, I tracked it down to here: https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/payment-gateway/class-sv-wc-payment-gateway-hosted.php#L416

Even if the payment was cancelled, the user is redirected to the thank you page. This is odd and creates confusion - "did it still go though, even though I cancelled??" Of course it did not, but the thank you page sends a wrong message.

Shouldn't we use `$order->get_cancel_order_url()` here instead, if the order status is `cancelled`? It looks like that simply redirect back to the cart, and the cart will be empty by that time. It should probably display a nice message "Your payment was cancelled" or something.

Or perhaps even better - redirect to the order pay page - or not empty the cart. Because - one might cancel the payment simply because they chose that particular gateway by mistake and intended to use another. In that case, they still would want to pay and should be able to do so.

**Comment by maxrice** [comment]
moving this to 3.3 milestone so we can use the `WC_Order::get_cancel_order_url_raw()` method and backport to 2.2/2.3

**Comment by tamarazuk** [comment]
the compat method already backports to all WC versions which do not include that new method - see https://github.com/skyverge/wc-plugin-framework/commit/722cf8dea34b98273aa6e97cc9a861fc96da688a#diff-a91cff3a19d567c1568891387c707237R259. So I think we only need to replace all instances of `WC_Order::get_cancel_order_url_raw()` with `SV_WC_Plugin_Compatibility:: get_cancel_order_url_raw ()`

**Comment by maxrice** [comment]
moving this to 4.1, I'm not entirely sure what needs to be changed here with our implementation and we're out of time for 4.0

**Comment by ragulka** [comment]
I've looked at the core implementation, namely PayPal and Simplify Commerce, where the `WC_Order::get_cancel_order_url()` method is used. This method returns a URL which, when visited, cancels the order and restores the cart (if it was available before trying to make the payment):

However, there are 2 distinctive use cases/behaviours to this:

1. Paying from cart -> checkout. When adding products to cart, going to checkout, selecting PayPal and then cancelling the payment on PayPal: order is cancelled, cart is restored and user is redirected to the cart with a notice "Your order was cancelled".

2. Paying from my account -> order -> pay. When selecting PayPal and then cancelling the payment on PayPal: order is cancelled and user is redirected to an empty cart page.

This is the core implementation. However, I am not sure I quite agree that no. 2 is a good approach UX-wise. What if I accidentally selected PayPal? I want to cancel the payment from PayPal, but want to still pay using another method, perhaps BACS. But I can't do that because as soon as I click cancel on PayPal, the order itself is fully cancelled with no way to pay for it or even restore the cart (there's no Order Again button for cancelled orders).

I know this is probably an edge-case, so not sure if we should do anything about it... although I have a gut feeling that this might actually affect conversions in stores, even if only slightly. Imagine you had created a gigantic order and chose the wrong payment method by mistake and now you're like "what?!? i have to do it all over again?!?".

In any case, our framework implementation is misleading as it is - when an order is cancelled, customer is redirected to the thank you page, which is confusing. We should at least follow core implementation here and redirect to the cancel endpoint, I think?
