### ISSUE TITLE
Cleanup payment gateway customer id handling

### ISSUE THREAD

**Issue by justinstern** [skyverge/wc-plugin-framework#66]
It's a bit of a mess, mostly thanks to the framework development initially being done with Intuit QBMS, which is a rare gateway that either auto-generates or allows you to generate a customer id, which then must be used in tokenization requests, iirc.  The related code in the direct payment gateway class is complex, messy, and difficult to follow, and should be refactored and simplified now that we have a number of frameworked tokenization gateways to draw from.

I've made a start on this (uncommitted)

**Comment by maxrice** [comment]
closed in https://github.com/skyverge/wc-plugins/commit/364a3ae1470a15d7c48bda7eea5a52ea9c50fc8d
