### ISSUE TITLE
Replace relative path includes with absolute paths

### ISSUE THREAD

**Issue by tamarazuk** [skyverge/wc-plugin-framework#74]
For some reason some servers hate relative paths when including PHP files. Let's replace these with absolute paths.

https://woothemes.zendesk.com/agent/tickets/259928

**Comment by maxrice** [comment]
probably best to do this as part of WC 2.4 compat, moving to 3.3 milestone

**Comment by tamarazuk** [comment]
Yeah I agree. it's scheduled for 2.4 compat in wc-plugins - skyverge/wc-plugins#640
