### ISSUE TITLE
Add admin notice when Subscriptions support is disabled due to a gateway setting

### ISSUE THREAD

**Issue by maxrice** [skyverge/wc-plugin-framework#82]
Certain gateways that support Subscriptions don't have tokenization enabled by default because it requires some additional action to be taken first within the merchant account. This can be confusing for the merchant when they've enabled the gateway but it doesn't appear in the list of payment gateways available for Subscriptions.

Let's render a notice in the settings admin when Subscriptions is active, but support is disabled due to a specific setting (e.g. tokenization is disabled)

see https://github.com/skyverge/wc-plugins/issues/309

**Comment by maxrice** [comment]
sample:

<img width="1113" alt="screen shot 2015-07-20 at 10 46 15 pm" src="https://cloud.githubusercontent.com/assets/1579862/8792124/85defd1a-2f31-11e5-8733-ad18f485f27d.png">

**Comment by justinstern** [comment]
might be cool if there was a way to add them to some list in the Subscriptions page, with the message about needing to enable tokenization to enable support

**Comment by maxrice** [comment]
Yeah, a gateway that supports subscriptions but doesn't have tokenization enabled will be hidden in the Subscriptions settings page. Unfortunately there's no way to filter that or change it from our end without JS :boar:

**Comment by thenbrent** [comment]
> might be cool if there was a way to add them to some list in the Subscriptions page

There is a section similar to that on the **WooCommerce > Settings > Checkout** screen: https://cloudup.com/cuBGrrrTb3q

We hook into that table using the `'woocommerce_payment_gateways_setting_columns'` filter, then add the content using the `'woocommerce_payment_gateways_setting_column_renewals'` action. Unfortunately, it's an action, so it's not easy as is for you guys to override that content and add your own informational/instructive notice, but we can add a filter in `payment_gateways_rewewal_support()` you guys could use?

Worth mentioning, this is a _very_ specific approach to addressing the immediate issue at hand, it isn't transferable to any other use case.

**Comment by maxrice** [comment]
reopening for improvements with Subscriptions 2.0

**Comment by maxrice** [comment]
Decided to focus exclusively on the gateways table rather than the settings page, since I think that's already covered by the admin notices. The table now looks like this with Subs 2.0:

![screen shot 2015-08-21 at 7 19 33 pm](https://cloud.githubusercontent.com/assets/1579862/9421166/9fb31590-483c-11e5-93f6-dddf038d8c03.png)

**Comment by maxrice** [comment]
finally resolved in 57e00dfc84b1e02da5f9494f2e6a3d05d6f99339
