### ISSUE TITLE
Support core WP dismissible admin notices

### ISSUE THREAD

**Issue by maxrice** [skyverge/wc-plugin-framework#93]
As of WP 4.2, core has [dismissible admin notices](https://make.wordpress.org/core/2015/04/23/spinners-and-dismissible-admin-notices-in-4-2/) -- much nicer: http://cl.ly/image/2m1g2b2J001L than our "dismiss" text.

Our existing [admin notice handler](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/class-sv-wc-admin-notice-handler.php) should be updated to use those notices if WP >= 4.2 -- eventually we can remove our dismissible handling once WC core requires WP 4.2+

Also should change the default notice class to `updated` as right now it's an angry red which doesn't fit most of our usages where the notice is just a friendly "hey check this out" vs. "omg something's wrong"

**Comment by justinstern** [comment]
woot! It'd be huge to be able to cut the dismissible admin notice code out, that stuff was pretty complicated to implement, and more complicated to use than I would have liked
