### ISSUE TITLE
SV_WC_Payment_Gateway_Direct::process_payment

### ISSUE THREAD

**Issue by tivnet** [skyverge/wc-plugin-framework#96]
I am not sure how to PR this. Too many "unknowns".

- the parent method returns `array()`, so this method should return array, too
- `$result = apply_filters( 'wc_payment_gateway_'` is compared to `true` (?) and then there is return without checking what is returned. Should still be an array (?)
- nothing returned in `catch` and nothing returned by default at the end.

**Comment by maxrice** [comment]
merged in SHA aa04bc81acadc5ac8c0f83aca19f475504550e5c
